### ISSUE TITLE
App.js in assets

### ISSUE THREAD

**Issue by RhodesPeter** [FAC10/week4-ammp#73]
Should app.js be in the assets folder? 

![screen shot 2017-03-17 at 10 34 45](https://cloud.githubusercontent.com/assets/18164707/24039690/feb7ddac-0afd-11e7-9cd7-8d5a53c9068f.png)

**Comment by RhodesPeter** [comment]
Or style.css

**Comment by akinsho** [comment]
Hi we discussed this and wanted to have these here as we felt that they were front end assets and that subfolders for one file each would be excessive @RhodesPeter

**Comment by RhodesPeter** [comment]
Assets should only be for pictures/favicons etc.

style.css and app.js should be in public if not in separate folders.

**Comment by RhodesPeter** [comment]
I have been told that this probably doesn't matter 😀
